const avatar = require("../assets/images/Avatar.png");
const avatar2 = require("../assets/images/Avatar2.png");
const bride = require("../assets/images/bride.png");
const discover = require("../assets/images/discover.png");
const explore = require("../assets/images/explore.png");
const explorer1 = require("../assets/images/explorer1");
const invitation = require("../assets/images/IV.png");
const lagos_owambe = require("../assets/images/lagos-owambe.png");
const north_central = require("../assets/images/NorthCentral.png");
const north_east = require("../assets/images/NorthEast.png");
const north_west = require("../assets/images/NorthWest.png");
const owanbe_black = require("../assets/images/owanbe-black.png");
const owanbe_red = require("../assets/images/owanbe-red.png");
const owanbe_white = require("../assets/images/owanbe-white.png");
const party_dancer = require("../assets/images/party-dancer.png");
const party = require("../assets/images/party.png");
const south_west = require("../assets/images/SouthWest.png");
const tag_partner1 = require("../assets/images/tag-partner1.png");
const tag_partner2 = require("../assets/images/tag-partner2.png");
const tag_partner3 = require("../assets/images/tag-partner3.png");
const tag_partner4 = require("../assets/images/tag-partner4.png");
const trad_wedding = require("../assets/images/trad-wedding.png");
const white_wedding = require("../assets/images/white-wedding.png");

export default {};
